/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestordeproyectos.view.admin;

import gestordeproyectos.dao.DepartamentoDao;
import gestordeproyectos.dao.EmpleadoDao;
import gestordeproyectos.dto.DepartamentoDto;
import gestordeproyectos.dto.EmpleadoDto;
import gestordeproyectos.dto.RolDto;
import gestordeproyectos.util.*;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Irvin
 */
public class Departamentos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Departamentos
     */
    public static boolean isOpen = false;

    private List<DepartamentoDto> departamentos;
    private List<EmpleadoDto> empleados;
    private DepartamentoDto nuevoDepartamento;
    private EmpleadoDto jefeDesarrollo;
    private EmpleadoDto jefeDepartamento;
    Object[][] datos;
    final String[] COLUMNAS;
    final DepartamentoDao DEPARTAMENTO_DAO;
    final EmpleadoDao EMPLEADO_DAO;

    
    public Departamentos() {
        initComponents();
        btnActualizar.setEnabled(false);
        String[] cols = {"Id", "Nombre", "Jefe de desarrollo", "Jefe de departamento"};
        isOpen = true;
        COLUMNAS = cols;
        DEPARTAMENTO_DAO = new DepartamentoDao();
        EMPLEADO_DAO = new EmpleadoDao();
        departamentos = DEPARTAMENTO_DAO.list();
        empleados = EMPLEADO_DAO.list();
        fillTable();
        txtIdDepartamento.setDocument(new JTextFieldLimit(3));
        txtNombresDepartamento.setDocument(new JTextFieldLimit(50));
        txtBuscarDepartamento.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
            fillTable();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
            fillTable();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            fillTable();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdDepartamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombresDepartamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtJefeDesarrollo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtJefeDepartamento = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtBuscarDepartamento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDepartamentos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("..:Departamento:.."));

        jLabel2.setText("id");

        jLabel3.setText("Nombre");

        jLabel1.setText("Jefe de desarrollo");

        txtJefeDesarrollo.setEditable(false);
        txtJefeDesarrollo.setEnabled(false);

        jLabel4.setText("Jefe de departamento");

        txtJefeDepartamento.setEditable(false);
        txtJefeDepartamento.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(txtIdDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(110, 110, 110)
                        .addComponent(txtNombresDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJefeDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txtJefeDesarrollo))))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombresDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtJefeDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJefeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("..:Controles de departamentos:.."));

        btnIngresar.setText("Ingresar nuevo departamento");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar departamento");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIngresar)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("..:Departamentos:.."));

        jLabel10.setText("Buscar departamento por nombre");

        jTableDepartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDepartamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableDepartamentos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jTableDepartamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDepartamentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDepartamentos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txtBuscarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtBuscarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        String name = txtNombresDepartamento.getText().trim();
        String id = txtIdDepartamento.getText().toUpperCase();
        
        DepartamentoDto departamento = DEPARTAMENTO_DAO.read(id);
        
        
        if (name.isBlank()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Debes ingresar un nombre",
                    "Nombre vacío",
                    JOptionPane.ERROR_MESSAGE
            );
        }

        if (id.length() < 3) {
            JOptionPane.showMessageDialog(
                    this,
                    "Debes ingreser un id de tres caracteres",
                    "Id incorrecto",
                    JOptionPane.ERROR_MESSAGE
            );
        }
        
        if (departamento != null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ya existe un departamento con este id, intenta uno nuevo",
                    "Id ocupado",
                    JOptionPane.ERROR_MESSAGE
            );
        }

        if (departamento == null && !name.isBlank() && id.length() == 3) {
            nuevoDepartamento = new DepartamentoDto(id, name);
            DEPARTAMENTO_DAO.insert(nuevoDepartamento);

            JOptionPane.showMessageDialog(
                    this,
                    "Departamento ingresado correctamente",
                    "Departamento ingresado",
                    JOptionPane.INFORMATION_MESSAGE
            );
            clear();
            departamentos = DEPARTAMENTO_DAO.list();
            fillTable();
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        String name = txtNombresDepartamento.getText().trim();
        if (name.isBlank()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Debes ingresar un nombre",
                    "Nombre vacío",
                    JOptionPane.ERROR_MESSAGE
            );
        } else {
            nuevoDepartamento.setNombreDepartamento(name);
            DEPARTAMENTO_DAO.update(nuevoDepartamento);

            JOptionPane.showMessageDialog(
                    this,
                    "Departamento ingresado correctamente",
                    "Departamento ingresado",
                    JOptionPane.INFORMATION_MESSAGE
            );
            clear();
            departamentos = DEPARTAMENTO_DAO.list();
            fillTable();
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        isOpen = false;
    }//GEN-LAST:event_formInternalFrameClosing

    private void jTableDepartamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDepartamentosMouseClicked
        // TODO add your handling code here:
        int fila = jTableDepartamentos.rowAtPoint(evt.getPoint());
        if (fila > -1) {
            
            nuevoDepartamento = DEPARTAMENTO_DAO.read((String) datos[fila][0]);
            jefeDepartamento = EMPLEADO_DAO.getJefeDepartamento(nuevoDepartamento);
            jefeDesarrollo = EMPLEADO_DAO.getJefeProgramador(nuevoDepartamento);
            //Se llena el panel de departamento
            txtIdDepartamento.setText(nuevoDepartamento.getIdDepartamento());
            txtNombresDepartamento.setText(nuevoDepartamento.getNombreDepartamento());
            
            //
            txtJefeDepartamento.setText(
                    jefeDepartamento == null
                            ? ""
                            : jefeDepartamento.getNombreEmpleado()
            );
            txtJefeDesarrollo.setText(
                    jefeDesarrollo == null
                            ? ""
                            : jefeDesarrollo.getNombreEmpleado()
            );
            txtIdDepartamento.setEnabled(false);
            btnActualizar.setEnabled(true);
            btnIngresar.setEnabled(false);
        }


    }//GEN-LAST:event_jTableDepartamentosMouseClicked
    private void clear() {
        nuevoDepartamento = null;
        jefeDepartamento = null;
        jefeDesarrollo = null;
        txtIdDepartamento.setText("");
        txtNombresDepartamento.setText("");
        btnActualizar.setEnabled(false);
        btnIngresar.setEnabled(true);
        txtIdDepartamento.setEnabled(true);
    }

    private void fillTable() {
        //posición de la fila
        int i = 0;
        String name = txtBuscarDepartamento.getText().trim().toLowerCase();
        List<DepartamentoDto> filteredList = new LinkedList<>();
        
        for (DepartamentoDto d : departamentos) {
            if (d.getNombreDepartamento().toLowerCase().contains(name)) {
                filteredList.add(d);
            }
        }
        //Object[j][i] j=fila i=columna
        datos = new Object[filteredList.size()][COLUMNAS.length];
        for (DepartamentoDto d : filteredList) {

            EmpleadoDto jDes = null;
            EmpleadoDto jFun = null;

            for (EmpleadoDto e : empleados) {
                
                if (e.getIdDepartamento() == null) {
                    continue;
                }
                if (e.getIdDepartamento().equals(d.getIdDepartamento())) {
                    if (e.getIdRol() == RolDto.JEFE_DESARROLLO) {
                        jDes = e;
                    }
                    if (e.getIdRol() == RolDto.JEFE_FUNCIONAL) {
                        jFun = e;
                    }
                }

                if (jDes != null && jFun != null) {
                    break;
                }
            }

            datos[i][0] = d.getIdDepartamento();
            datos[i][1] = d.getNombreDepartamento();
            datos[i][2] = jDes == null ? "" : jDes.getNombreEmpleado();
            datos[i][3] = jFun == null ? "" : jFun.getNombreEmpleado();
            i++;
        }

        DefaultTableModel dtm = new DefaultTableModel(datos, COLUMNAS);
        jTableDepartamentos.setModel(dtm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDepartamentos;
    private javax.swing.JTextField txtBuscarDepartamento;
    private javax.swing.JTextField txtIdDepartamento;
    private javax.swing.JTextField txtJefeDepartamento;
    private javax.swing.JTextField txtJefeDesarrollo;
    private javax.swing.JTextField txtNombresDepartamento;
    // End of variables declaration//GEN-END:variables
}
