/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestordeproyectos.view.jefefuncional;

import gestordeproyectos.dao.SolicitudDao;
import gestordeproyectos.dao.TipoSolicitudDao;
import gestordeproyectos.dto.DepartamentoDto;
import gestordeproyectos.dto.EstadoSolicitudDto;
import gestordeproyectos.dto.SolicitudDto;
import gestordeproyectos.dto.TipoSolicitudDto;
import gestordeproyectos.util.JTextFieldLimit;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Irvin
 */
public class NuevaSolicitud extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevoCaso
     */
    public static boolean isOpen = false;
    
    private final DepartamentoDto DEPARTAMENTO;
    private final List<TipoSolicitudDto> TIPOS_SOLICITUD;
    private final SolicitudDao SOLICITUD_DAO;

    public NuevaSolicitud(DepartamentoDto departamento) {
        isOpen = true;
        initComponents();
        txtDescipcion.setDocument(new JTextFieldLimit(2184));
        TIPOS_SOLICITUD = new TipoSolicitudDao().list();
        SOLICITUD_DAO = new SolicitudDao();
        DEPARTAMENTO = departamento;
        cmbSolicitud.removeAllItems();
        TIPOS_SOLICITUD.forEach(
                ts -> cmbSolicitud.addItem(ts.getNombreTipoSolicitud())
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbSolicitud = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescipcion = new javax.swing.JTextArea();
        btnIngresar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setTitle("Nueva solicitud");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        cmbSolicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Tipo de solicitud");

        jLabel5.setText("Descripcion solicitud");

        txtDescipcion.setColumns(20);
        txtDescipcion.setLineWrap(true);
        txtDescipcion.setRows(5);
        txtDescipcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDescipcion);

        btnIngresar.setText("Solicitar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cmbSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cmbSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCancelar))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        String descripcion = txtDescipcion.getText().trim();
        int index = cmbSolicitud.getSelectedIndex();
        TipoSolicitudDto tipoSeleccionado = TIPOS_SOLICITUD.get(index);
        if (descripcion.isBlank()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Debes ingresar una descripción",
                    "Descripción vacía",
                    JOptionPane.ERROR_MESSAGE
            );
        } else {
            SolicitudDto nuevaSolicitud = new SolicitudDto(
                    EstadoSolicitudDto.EN_ESPERA,
                    DEPARTAMENTO.getIdDepartamento(),
                    tipoSeleccionado.getIdTipoSolicitud(),
                    descripcion
            );
            SOLICITUD_DAO.insert(nuevaSolicitud);

            JOptionPane.showMessageDialog(
                    this,
                    "Solicitud ingresada correctamente",
                    "Solicitud ingresada",
                    JOptionPane.INFORMATION_MESSAGE
            );
            isOpen = false;
            this.dispose();
        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        cmbSolicitud.setSelectedIndex(0);
        txtDescipcion.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        isOpen = false;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        isOpen = false;
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbSolicitud;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescipcion;
    // End of variables declaration//GEN-END:variables
}
